/**
 * 15 Most Played Sports Worldwide with Correct Positions and Levels
 * Includes USA college systems (NJCAA, NAIA, NCAA Div I/II/III),
 * Canadian competition systems (U SPORTS, CFL, CPL, etc.) and major pro leagues.
 */

export interface SportWithPositions {
  id: string;
  name: string;
  /**
   * Shown next to the name everywhere a sport is chosen. A picker of 23
   * identical text rows is slow to scan; the glyph is what the eye lands on.
   * Emoji rather than image assets: nothing to bundle, nothing to load, and
   * it inherits the text colour and size.
   */
  emoji: string;
  positions: string[];
  levels: string[];
}

export const SPORTS_WITH_POSITIONS: SportWithPositions[] = [
  {
    id: "soccer",
    name: "Soccer",
    emoji: "⚽",
    positions: [
      "Goalkeeper",
      "Center Back",
      "Full Back",
      "Wing Back",
      "Defensive Midfielder",
      "Central Midfielder",
      "Attacking Midfielder",
      "Winger",
      "Striker",
    ],
    levels: [
      "Recreational",
      "Club / Academy",
      "High School",
      "Provincial (OPDL / EXCEL)",
      "MLS NEXT",
      "USL Academy",
      "NJCAA",
      "NAIA",
      "CCAA (Canada)",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "USL League Two",
      "NPSL",
      "UPSL",
      "League1 Ontario",
      "League1 British Columbia",
      "League1 Alberta",
      "PLSQ (Quebec)",
      "Semi-Pro",
      "MLS NEXT Pro",
      "USL League One",
      "USL Championship",
      "USL Super League",
      "Canadian Premier League (CPL)",
      "Northern Super League (Canada)",
      "NWSL",
      "MLS",
      "International",
    ],
  },
  {
    id: "basketball",
    name: "Basketball",
    emoji: "🏀",
    positions: [
      "Point Guard",
      "Shooting Guard",
      "Small Forward",
      "Power Forward",
      "Center",
    ],
    levels: [
      "Recreational",
      "AAU / Club",
      "High School",
      "Prep (NPA / OSBA)",
      "Provincial (Canada Basketball)",
      "NJCAA",
      "NAIA",
      "CCAA (Canada)",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "The Basketball League (TBL)",
      "NBL Canada",
      "CEBL (Canadian Elite Basketball)",
      "G League",
      "EuroLeague / EuroCup",
      "Basketball Africa League (BAL)",
      "WNBA",
      "NBA",
      "International",
    ],
  },
  {
    id: "cricket",
    name: "Cricket",
    emoji: "🏏",
    positions: ["Batsman", "Bowler", "All-rounder", "Wicket-keeper"],
    levels: [
      "Club",
      "School",
      "County / State",
      "Cricket Canada (Provincial)",
      "CEGEP (Canada)",
      "Minor League Cricket (USA)",
      "Major League Cricket (USA)",
      "Global T20 Canada",
      "First Class",
      "List A",
      "T20",
      "Test",
      "International",
    ],
  },
  {
    id: "tennis",
    name: "Tennis",
    emoji: "🎾",
    positions: ["Singles", "Doubles"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "ITF Juniors",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "USTA / Tennis Canada Circuit",
      "ITF World Tennis Tour",
      "Challenger",
      "ATP / WTA",
      "Grand Slam",
    ],
  },
  {
    id: "volleyball",
    name: "Volleyball",
    emoji: "🏐",
    positions: [
      "Setter",
      "Outside Hitter",
      "Middle Blocker",
      "Opposite Hitter",
      "Libero",
    ],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "Provincial (Volleyball Canada)",
      "NJCAA",
      "NAIA",
      "CCAA (Canada)",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "Pro Volleyball Federation",
      "LOVB",
      "AVP (Beach)",
      "Professional (Europe)",
      "International",
    ],
  },
  {
    id: "table-tennis",
    name: "Table Tennis",
    emoji: "🏓",
    positions: ["Singles", "Doubles"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "Provincial (Table Tennis Canada)",
      "College",
      "CEGEP (Canada)",
      "State / Regional",
      "National (USATT / TTCAN)",
      "ITTF World Tour",
      "Pan Am Games",
      "Olympic",
    ],
  },
  {
    id: "baseball",
    name: "Baseball",
    emoji: "⚾",
    positions: [
      "Pitcher",
      "Catcher",
      "First Baseman",
      "Second Baseman",
      "Third Baseman",
      "Shortstop",
      "Left Fielder",
      "Center Fielder",
      "Right Fielder",
    ],
    levels: [
      "Little League",
      "Minor / Travel",
      "High School",
      "Academy / Showcase",
      "Baseball Canada (Provincial)",
      "PBLO (Premier Baseball League of Ontario)",
      "NJCAA",
      "NAIA",
      "CCBC (Canadian College Baseball)",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "Summer Collegiate (Cape Cod / Northwoods / WCL)",
      "Frontier League",
      "American Association",
      "Pioneer League",
      "Atlantic League",
      "Minor League (MiLB)",
      "MLB",
      "International",
    ],
  },
  {
    id: "american-football",
    name: "American Football",
    emoji: "🏈",
    positions: [
      "Quarterback",
      "Running Back",
      "Wide Receiver",
      "Tight End",
      "Offensive Line",
      "Defensive Line",
      "Linebacker",
      "Defensive Back",
      "Kicker",
      "Punter",
    ],
    levels: [
      "Youth / Minor (Football Canada)",
      "Youth (Pop Warner)",
      "Flag Football",
      "High School",
      "Prep / Academy",
      "CEGEP (Canada)",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I (FCS)",
      "NCAA Div I (FBS)",
      "U SPORTS (Canada)",
      "OUA (U SPORTS Ontario)",
      "RSEQ (U SPORTS Quebec)",
      "Canada West (U SPORTS)",
      "AUS (U SPORTS Atlantic)",
      "CJFL (Canadian Junior Football)",
      "BCFC (BC Football Conference)",
      "PFC (Prairie Football Conference)",
      "OFC (Ontario Football Conference)",
      "QJFL (Quebec Junior Football)",
      "Senior Amateur / Semi-Pro",
      "AFL (Arena League)",
      "UFL",
      "CFL",
      "NFL",
      "ELF (European League of Football)",
      "International",
    ],
  },
  {
    id: "hockey",
    name: "Hockey",
    emoji: "🏒",
    positions: ["Center", "Left Wing", "Right Wing", "Defenseman", "Goalie"],
    levels: [
      "Recreational",
      "Minor Hockey (Hockey Canada / USA Hockey)",
      "AAA / Elite Minor",
      "High School",
      "Prep (CSSHL / NEPSAC)",
      "Junior C",
      "Junior B",
      "BCHL",
      "AJHL",
      "SJHL",
      "MJHL",
      "OJHL",
      "NOJHL",
      "CCHL",
      "MHL",
      "LHJAAAQ (Quebec Junior AAA)",
      "USHL",
      "NAHL",
      "NCDC",
      "QMJHL (Major Junior)",
      "OHL (Major Junior)",
      "WHL (Major Junior)",
      "NCAA Div III",
      "NCAA Div I",
      "ACHA",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "SPHL",
      "ECHL",
      "AHL",
      "PWHL",
      "NHL",
      "KHL / SHL / Liiga (Europe)",
      "International",
    ],
  },
  {
    id: "rugby",
    name: "Rugby",
    emoji: "🏉",
    positions: [
      "Prop",
      "Hooker",
      "Lock",
      "Flanker",
      "Number 8",
      "Scrum-half",
      "Fly-half",
      "Center",
      "Wing",
      "Fullback",
    ],
    levels: [
      "Club",
      "High School",
      "Provincial (Rugby Canada)",
      "College / University",
      "NAIA",
      "NCAA Emerging Sport",
      "CEGEP (Canada)",
      "Canadian Rugby Championship",
      "Semi-Pro",
      "MLR (Major League Rugby)",
      "Premiership / URC (Europe)",
      "Super Rugby",
      "International",
      "World Cup",
    ],
  },
  {
    id: "badminton",
    name: "Badminton",
    emoji: "🏸",
    positions: ["Singles", "Doubles", "Mixed Doubles"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "Provincial (Badminton Canada)",
      "College",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "National (USA Badminton / Badminton Canada)",
      "BWF Tour",
      "Pan Am Games",
      "Olympic",
    ],
  },
  {
    id: "swimming",
    name: "Swimming",
    emoji: "🏊",
    positions: [
      "Freestyle",
      "Backstroke",
      "Breaststroke",
      "Butterfly",
      "Individual Medley",
    ],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "Provincial (Swimming Canada)",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "National (USA Swimming / Swimming Canada)",
      "Pan Am Games",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "golf",
    name: "Golf",
    emoji: "⛳",
    positions: ["Professional", "Amateur"],
    levels: [
      "Recreational",
      "Club",
      "Junior (AJGA / Maple Leaf Junior Tour)",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "Amateur (Golf Canada / USGA)",
      "PGA TOUR Americas",
      "Korn Ferry Tour",
      "Epson Tour",
      "LPGA",
      "PGA TOUR",
      "Major Championships",
    ],
  },
  {
    id: "lacrosse",
    name: "Lacrosse",
    emoji: "🥍",
    positions: ["Attack", "Midfield", "Defense", "Goalie"],
    levels: [
      "Recreational",
      "Youth / Minor",
      "High School",
      "Junior B",
      "Junior A (OJLL / BCJALL / RMLL)",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "Canadian Lacrosse Association (Senior)",
      "NLL (National Lacrosse League)",
      "PLL (Premier Lacrosse League)",
      "Athletes Unlimited",
      "International",
    ],
  },
  {
    id: "track-field",
    name: "Track & Field",
    emoji: "🏃",
    positions: ["Sprints", "Distance", "Hurdles", "Jumps", "Throws"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "Provincial (Athletics Canada)",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "National (USATF / Athletics Canada)",
      "NACAC",
      "Diamond League",
      "World Championships",
      "Olympic",
    ],
  },
  // ── Flag Football — Olympic sport as of LA 2028; fast-growing worldwide. ──
  {
    id: "flag-football",
    name: "Flag Football",
    emoji: "🏈",
    positions: [
      "Quarterback",
      "Center",
      "Wide Receiver",
      "Rusher",
      "Blitzer",
      "Safety",
      "Cornerback",
    ],
    levels: [
      "Youth",
      "NFL FLAG",
      "High School",
      "Club",
      "Provincial (Football Canada Flag)",
      "College Club",
      "NAIA (Emerging Sport)",
      "AFFL",
      "National Team",
      "IFAF World Championship",
      "Olympic (LA 2028)",
    ],
  },
  // ── Summer Olympic sports ──
  {
    id: "wrestling",
    name: "Wrestling",
    emoji: "🤼",
    positions: ["Freestyle", "Greco-Roman", "Folkstyle"],
    levels: [
      "Youth / Club",
      "High School",
      "Provincial (Wrestling Canada)",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "U SPORTS (Canada)",
      "National (USA Wrestling / Wrestling Canada)",
      "UWW Ranking Series",
      "Pan Am Games",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "gymnastics",
    name: "Gymnastics",
    emoji: "🤸",
    positions: [
      "All-Around",
      "Vault",
      "Floor Exercise",
      "Balance Beam",
      "Uneven Bars",
      "Pommel Horse",
      "Rings",
      "Parallel Bars",
    ],
    levels: [
      "Recreational",
      "Club",
      "Provincial (Gymnastics Canada)",
      "Xcel",
      "Level 10 / Elite Development",
      "NCAA Div II",
      "NCAA Div I",
      "National (USA Gymnastics / Gymnastics Canada)",
      "World Cup",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "softball",
    name: "Softball",
    emoji: "🥎",
    positions: [
      "Pitcher",
      "Catcher",
      "First Base",
      "Second Base",
      "Third Base",
      "Shortstop",
      "Outfield",
      "Designated Player",
    ],
    levels: [
      "Little League",
      "Minor / Travel",
      "High School",
      "Provincial (Softball Canada)",
      "Junior / U19",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "National (USA Softball / Softball Canada)",
      "Athletes Unlimited",
      "WPF (Women's Pro Fastpitch)",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "boxing",
    name: "Boxing",
    emoji: "🥊",
    positions: [
      "Flyweight",
      "Bantamweight",
      "Featherweight",
      "Lightweight",
      "Welterweight",
      "Middleweight",
      "Light Heavyweight",
      "Heavyweight",
    ],
    levels: [
      "Amateur",
      "Club",
      "Provincial (Boxing Canada)",
      "Golden Gloves",
      "Collegiate (NCBA)",
      "National (USA Boxing / Boxing Canada)",
      "Elite / Elite+",
      "Pan Am Games",
      "World Championships",
      "Olympic",
      "Professional",
    ],
  },
  {
    id: "fitness",
    name: "Fitness",
    emoji: "🏋️",
    // Fitness is a discipline, not a position sport, so "position" is the
    // thing someone actually does -- which is what a coach searching for a
    // powerlifter or a HYROX athlete is filtering on.
    positions: [
      "Personal Training",
      "Strength & Conditioning",
      "Bodybuilding",
      "Physique",
      "Powerlifting",
      "Olympic Weightlifting",
      "CrossFit",
      "Functional Fitness",
      "HYROX",
      "Calisthenics",
      "Strongman",
      "Group Fitness",
      "Endurance / Hybrid",
      "Other",
    ],
    // Reads as a career for both sides: an athlete's competition level and a
    // coach's certification sit on the same ladder here, because in fitness
    // they genuinely do.
    levels: [
      "Recreational",
      "Gym / Club",
      "High School",
      "Certified Trainer (NASM / ACE / ISSA)",
      "canfitpro / CSEP (Canada)",
      "CSCS (Strength & Conditioning)",
      "CEGEP (Canada)",
      "College / University S&C",
      "NCAA Strength & Conditioning",
      "U SPORTS (Canada)",
      "CrossFit Affiliate",
      "Provincial / Regional",
      "National",
      "NPC / IFBB",
      "CrossFit Games",
      "HYROX Elite",
      "World Championships",
      "Olympic (Weightlifting)",
      "Professional",
    ],
  },
  // ── Winter Olympic sports ──
  {
    id: "alpine-skiing",
    name: "Alpine Skiing",
    emoji: "⛷️",
    positions: ["Slalom", "Giant Slalom", "Super-G", "Downhill", "Combined"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "Provincial (Alpine Canada)",
      "U.S. Ski & Snowboard Development",
      "NCAA",
      "FIS",
      "NorAm Cup",
      "Europa Cup",
      "National Team",
      "World Cup",
      "Olympic",
    ],
  },
  {
    id: "snowboarding",
    name: "Snowboarding",
    emoji: "🏂",
    positions: [
      "Halfpipe",
      "Slopestyle",
      "Big Air",
      "Snowboard Cross",
      "Parallel Slalom",
    ],
    levels: [
      "Recreational",
      "Club",
      "Provincial (Canada Snowboard)",
      "U.S. Ski & Snowboard Development",
      "FIS",
      "NorAm Cup",
      "National Team",
      "World Cup",
      "X Games",
      "Olympic",
    ],
  },
  {
    id: "figure-skating",
    name: "Figure Skating",
    emoji: "⛸️",
    positions: ["Singles", "Pairs", "Ice Dance", "Synchronized"],
    levels: [
      "Learn to Skate",
      "Club",
      "STAR / Regional",
      "Sectional",
      "Provincial",
      "National (U.S. Figure Skating / Skate Canada)",
      "Challenger Series",
      "ISU Grand Prix",
      "Four Continents",
      "World Championships",
      "Olympic",
    ],
  },
];

/**
 * The emoji for a sport NAME, '' when we do not know it.
 *
 * Lookup is by name because that is what every screen stores and passes
 * around -- profiles, filters and the onboarding questions all hold the
 * display name, not the id. The aliases cover the shorter labels the
 * onboarding questions use ("Football", "Track") so those rows get a glyph
 * too instead of being the only bare ones.
 */
const SPORT_EMOJI_BY_NAME: Record<string, string> = {
  ...Object.fromEntries(
    SPORTS_WITH_POSITIONS.map((s) => [s.name.toLowerCase(), s.emoji]),
  ),
  football: "\u{1F3C8}",
  track: "\u{1F3C3}",
  mma: "\u{1F94B}",
  "martial arts": "\u{1F94B}",
  other: "\u{1F3C5}",
};

export const sportEmoji = (name: string | null | undefined): string =>
  name ? (SPORT_EMOJI_BY_NAME[name.trim().toLowerCase()] ?? "") : "";
