/**
 * 15 Most Played Sports Worldwide with Correct Positions and Levels
 * Includes USA college systems (NJCAA, NAIA, NCAA Div I/II/III),
 * Canadian competition systems (U SPORTS, CFL, CPL, etc.) and major pro leagues.
 */

export interface SportWithPositions {
  id: string;
  name: string;
  positions: string[];
  levels: string[];
}

export const SPORTS_WITH_POSITIONS: SportWithPositions[] = [
  {
    id: "soccer",
    name: "Soccer",
    positions: [
      "Goalkeeper",
      "Center Back",
      "Full Back",
      "Wing Back",
      "Defensive Midfielder",
      "Central Midfielder",
      "Attacking Midfielder",
      "Winger",
      "Striker",
    ],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "CPL (Canadian Premier League)",
      "Semi-Pro",
      "MLS/NWSL",
      "International",
    ],
  },
  {
    id: "basketball",
    name: "Basketball",
    positions: [
      "Point Guard",
      "Shooting Guard",
      "Small Forward",
      "Power Forward",
      "Center",
    ],
    levels: [
      "Recreational",
      "AAU",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "NBL Canada",
      "CEBL (Canadian Elite Basketball)",
      "G-League",
      "NBA/WNBA",
      "International",
    ],
  },
  {
    id: "cricket",
    name: "Cricket",
    positions: ["Batsman", "Bowler", "All-rounder", "Wicket-keeper"],
    levels: [
      "Club",
      "County/State",
      "Cricket Canada (Provincial)",
      "CEGEP (Canada)",
      "First Class",
      "List A",
      "T20",
      "Test",
      "International",
    ],
  },
  {
    id: "tennis",
    name: "Tennis",
    positions: ["Singles", "Doubles"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "USTA / Tennis Canada Circuit",
      "Challenger",
      "ATP/WTA",
      "Grand Slam",
    ],
  },
  {
    id: "volleyball",
    name: "Volleyball",
    positions: [
      "Setter",
      "Outside Hitter",
      "Middle Blocker",
      "Opposite Hitter",
      "Libero",
    ],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "Professional",
      "International",
    ],
  },
  {
    id: "table-tennis",
    name: "Table Tennis",
    positions: ["Singles", "Doubles"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "College",
      "CEGEP (Canada)",
      "State/Provincial",
      "National (USATT / TTC)",
      "ITTF",
      "Olympic",
    ],
  },
  {
    id: "baseball",
    name: "Baseball",
    positions: [
      "Pitcher",
      "Catcher",
      "First Baseman",
      "Second Baseman",
      "Third Baseman",
      "Shortstop",
      "Left Fielder",
      "Center Fielder",
      "Right Fielder",
    ],
    levels: [
      "Little League",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "Canadian Amateur (Baseball Canada)",
      "Minor League (MiLB)",
      "MLB",
      "International",
    ],
  },
  {
    id: "american-football",
    name: "American Football",
    positions: [
      "Quarterback",
      "Running Back",
      "Wide Receiver",
      "Tight End",
      "Offensive Line",
      "Defensive Line",
      "Linebacker",
      "Defensive Back",
      "Kicker",
      "Punter",
    ],
    levels: [
      "Youth",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I (FCS)",
      "NCAA Div I (FBS)",
      "CEGEP (Canada)",
      "CJFL (Canadian Jr Football)",
      "CFL",
      "AFL (Arena League)",
      "NFL",
      "International",
    ],
  },
  {
    id: "hockey",
    name: "Hockey",
    positions: ["Center", "Left Wing", "Right Wing", "Defenseman", "Goalie"],
    levels: [
      "Recreational",
      "Youth",
      "High School",
      "Junior A/B (BCHL / AJHL / NOJHL)",
      "QMJHL (Major Junior)",
      "OHL (Major Junior)",
      "WHL (Major Junior)",
      "NCAA Div III",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "ECHL",
      "AHL",
      "NHL",
      "International",
    ],
  },
  {
    id: "rugby",
    name: "Rugby",
    positions: [
      "Prop",
      "Hooker",
      "Lock",
      "Flanker",
      "Number 8",
      "Scrum-half",
      "Fly-half",
      "Center",
      "Wing",
      "Fullback",
    ],
    levels: [
      "Club",
      "High School",
      "College",
      "NAIA",
      "NCAA Emerging Sport",
      "CEGEP (Canada)",
      "Semi-Pro",
      "Rugby Canada Cup",
      "MLR",
      "International",
      "World Cup",
    ],
  },
  {
    id: "badminton",
    name: "Badminton",
    positions: ["Singles", "Doubles", "Mixed Doubles"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "College",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "State/Provincial",
      "National (USA Badminton / Badminton Canada)",
      "BWF",
      "Olympic",
    ],
  },
  {
    id: "swimming",
    name: "Swimming",
    positions: [
      "Freestyle",
      "Backstroke",
      "Breaststroke",
      "Butterfly",
      "Individual Medley",
    ],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "National (USA Swimming / Swimming Canada)",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "golf",
    name: "Golf",
    positions: ["Professional", "Amateur"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "Amateur",
      "Mackenzie Tour – PGA TOUR Canada",
      "PGA/LPGA",
      "Major Championships",
    ],
  },
  {
    id: "lacrosse",
    name: "Lacrosse",
    positions: ["Attack", "Midfield", "Defense", "Goalie"],
    levels: [
      "Recreational",
      "Youth",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "Canadian Junior Lacrosse League",
      "U SPORTS (Canada)",
      "NLL (National Lacrosse League)",
      "MLL/PLL",
      "International",
    ],
  },
  {
    id: "track-field",
    name: "Track & Field",
    positions: ["Sprints", "Distance", "Hurdles", "Jumps", "Throws"],
    levels: [
      "Recreational",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "U SPORTS (Canada)",
      "National (USATF / Athletics Canada)",
      "World Championships",
      "Olympic",
    ],
  },
  // ── Flag Football — Olympic sport as of LA 2028; fast-growing worldwide. ──
  {
    id: "flag-football",
    name: "Flag Football",
    positions: [
      "Quarterback",
      "Center",
      "Wide Receiver",
      "Rusher",
      "Blitzer",
      "Safety",
      "Cornerback",
    ],
    levels: [
      "Youth",
      "High School",
      "Club",
      "College Club",
      "NAIA (Emerging Sport)",
      "National Team",
      "IFAF World Championship",
      "Olympic (LA 2028)",
    ],
  },
  // ── Summer Olympic sports ──
  {
    id: "wrestling",
    name: "Wrestling",
    positions: ["Freestyle", "Greco-Roman", "Folkstyle"],
    levels: [
      "Youth",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "U SPORTS (Canada)",
      "National (USA Wrestling / Wrestling Canada)",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "gymnastics",
    name: "Gymnastics",
    positions: [
      "All-Around",
      "Vault",
      "Floor Exercise",
      "Balance Beam",
      "Uneven Bars",
      "Pommel Horse",
      "Rings",
      "Parallel Bars",
    ],
    levels: [
      "Recreational",
      "Club",
      "Level 10 / Elite Development",
      "NCAA Div II",
      "NCAA Div I",
      "National (USA Gymnastics / Gymnastics Canada)",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "softball",
    name: "Softball",
    positions: [
      "Pitcher",
      "Catcher",
      "First Base",
      "Second Base",
      "Third Base",
      "Shortstop",
      "Outfield",
      "Designated Player",
    ],
    levels: [
      "Little League",
      "High School",
      "NJCAA",
      "NAIA",
      "NCAA Div III",
      "NCAA Div II",
      "NCAA Div I",
      "CEGEP (Canada)",
      "National (USA Softball / Softball Canada)",
      "World Championships",
      "Olympic",
    ],
  },
  {
    id: "boxing",
    name: "Boxing",
    positions: [
      "Flyweight",
      "Bantamweight",
      "Featherweight",
      "Lightweight",
      "Welterweight",
      "Middleweight",
      "Light Heavyweight",
      "Heavyweight",
    ],
    levels: [
      "Amateur",
      "Club",
      "Golden Gloves",
      "Collegiate (NCBA)",
      "National (USA Boxing / Boxing Canada)",
      "World Championships",
      "Olympic",
      "Professional",
    ],
  },
  // ── Winter Olympic sports ──
  {
    id: "alpine-skiing",
    name: "Alpine Skiing",
    positions: ["Slalom", "Giant Slalom", "Super-G", "Downhill", "Combined"],
    levels: [
      "Recreational",
      "Club",
      "High School",
      "U.S. Ski & Snowboard / Alpine Canada Development",
      "NCAA",
      "National Team",
      "World Cup",
      "Olympic",
    ],
  },
  {
    id: "snowboarding",
    name: "Snowboarding",
    positions: [
      "Halfpipe",
      "Slopestyle",
      "Big Air",
      "Snowboard Cross",
      "Parallel Slalom",
    ],
    levels: [
      "Recreational",
      "Club",
      "U.S. Ski & Snowboard / Canada Snowboard Development",
      "National Team",
      "World Cup",
      "X Games",
      "Olympic",
    ],
  },
  {
    id: "figure-skating",
    name: "Figure Skating",
    positions: ["Singles", "Pairs", "Ice Dance", "Synchronized"],
    levels: [
      "Learn to Skate",
      "Club",
      "Regional",
      "Sectional",
      "National (U.S. Figure Skating / Skate Canada)",
      "ISU Grand Prix",
      "World Championships",
      "Olympic",
    ],
  },
];
