-- ============================================================
-- MIGRATIONS À EXÉCUTER MANUELLEMENT (ordre strict)
-- Generated by the Phase 0-6 backend audit.
-- This file aggregates every NEW migration produced by the audit.
-- The 7 pre-existing migrations (001..007) are NOT included here.
-- ============================================================

-- ------------------------------------------------------------
-- -- MIGRATION À EXÉCUTER MANUELLEMENT --
-- 008_audit_constraints_and_indexes.sql
-- ------------------------------------------------------------

-- 1. Defense-in-depth against self-swipe (the service blocks it too).
ALTER TABLE public.swipes
  DROP CONSTRAINT IF EXISTS swipes_no_self_swipe;
ALTER TABLE public.swipes
  ADD CONSTRAINT swipes_no_self_swipe CHECK (swiper_id <> swiped_id);

-- 2. CHECK on subscriptions.plan_id mirrors users.plan_id (consistency).
ALTER TABLE public.subscriptions
  DROP CONSTRAINT IF EXISTS subscriptions_plan_id_check;
ALTER TABLE public.subscriptions
  ADD CONSTRAINT subscriptions_plan_id_check
  CHECK (plan_id IN ('basic', 'starter', 'pro', 'premium'));

-- 3. Index for subscription lookup by Stripe subscription id (used in webhooks).
CREATE INDEX IF NOT EXISTS idx_subscriptions_stripe_subscription_id
  ON public.subscriptions(stripe_subscription_id)
  WHERE stripe_subscription_id IS NOT NULL;

-- 4. Index for unique (viewer, viewed) profile-view dedup queries.
CREATE INDEX IF NOT EXISTS idx_profile_views_viewer_viewed
  ON public.profile_views(viewer_id, viewed_id, created_at DESC);

-- ------------------------------------------------------------
-- -- MIGRATION À EXÉCUTER MANUELLEMENT --
-- 009_user_preferences.sql
-- ------------------------------------------------------------
-- Per-user JSONB blob for client-managed settings (notification
-- toggles, privacy flags). Client owns the schema of the contents.
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS preferences JSONB NOT NULL DEFAULT '{}'::jsonb;

-- ------------------------------------------------------------
-- -- MIGRATION À EXÉCUTER MANUELLEMENT --
-- 010_signup_otps.sql
-- ------------------------------------------------------------
-- Backend-owned OTP storage for the new email + phone signup flow.
-- A Supabase auth user is created only after `/auth/complete-signup`.
CREATE TABLE IF NOT EXISTS public.signup_otps (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  contact       TEXT NOT NULL,
  contact_type  TEXT NOT NULL CHECK (contact_type IN ('email', 'phone')),
  code_hash     TEXT NOT NULL,
  attempts      INT  NOT NULL DEFAULT 0,
  verified      BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at    TIMESTAMPTZ NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_signup_otps_contact
  ON public.signup_otps(contact, contact_type);
CREATE INDEX IF NOT EXISTS idx_signup_otps_expires_at
  ON public.signup_otps(expires_at);
ALTER TABLE public.signup_otps ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------
-- -- MIGRATION À EXÉCUTER MANUELLEMENT --
-- 011_users_phone.sql
-- ------------------------------------------------------------
-- Phone signup support: allow phone-only users, refresh trigger.
ALTER TABLE public.users
  ALTER COLUMN email DROP NOT NULL;
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS phone TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone_unique
  ON public.users(phone)
  WHERE phone IS NOT NULL;
ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS users_email_or_phone;
ALTER TABLE public.users
  ADD CONSTRAINT users_email_or_phone
  CHECK (email IS NOT NULL OR phone IS NOT NULL);
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, phone, role, name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.phone,
    COALESCE(NEW.raw_user_meta_data->>'role', 'athlete'),
    COALESCE(NEW.raw_user_meta_data->>'name', '')
  );
  INSERT INTO public.subscriptions (user_id, plan_id, daily_swipe_limit)
  VALUES (NEW.id, 'basic', 10);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
